[deps]
AnythingLLMDocs = "333fe5f5-19c9-4863-8caf-c9193e7dba62"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
QuantumInterface = "5717a53b-5d69-4fa3-b976-0bf2f97ca1e5"
QuantumOpticsBase = "4f57444f-1401-5e15-980d-4471b28d5678"

[compat]
Documenter = "1"
